### ISSUE TITLE
Running terraform multiple times on the same project throws error

### ISSUE THREAD

**Issue by rumbaugha** [GoogleCloudPlatform/terraform-google-load-balanced-vms#11]
When trying to run the terraform multiple times on the same project and error occurs with resource names. The first time it succeeds and it looks like it's trying to create the same subnet as the first run.

```
Error creating Subnetwork: googleapi: Error 409: The resource 'projects/bc-test-project-357822/regions/us-central1/subnetworks/subnet-01' already exists, alreadyExists
```

**Comment by joeysilva-g** [comment]
This should be re-opened if not already fixed

**Comment by bharathkkb** [comment]
https://github.com/GoogleCloudPlatform/terraform-google-load-balanced-vms/pull/17 in progress

**Comment by bharathkkb** [comment]
fixed by https://github.com/GoogleCloudPlatform/terraform-google-load-balanced-vms/pull/17
